NILE_RUNTIME := ../../nile/runtimes/c
CFLAGS       := -pipe -Wall -Werror -Wno-unused -Wno-uninitialized \
                -I$(NILE_RUNTIME) \
                -O3 -ffast-math \
                #-march=corei7 -mfpmath=sse -msse4.2 -mno-ssse3 \

%.o: %.c *.h Makefile.gcc
	$(CC) -c $(CFLAGS) $<

libgezira.a: gezira.o gezira-image.o
	$(AR) rcs $@ $^

clean:
	$(RM) *.o *.a
